---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: flags-gg
  labels:
    name: dashboard
    app: dashboard
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      name: dashboard
  template:
    metadata:
      labels:
        name: dashboard
        app: dashboard
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: dashboard
          image: containers.chewed-k8s.net/flags-gg/dashboard:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: NEXTAUTH_URL
              value: https://dashboard.flags.gg
            - name: NEXTAUTH_URL_INTERNAL
              value: https://$(DASHBOARD_PORT_3000_TCP_ADDR)
            - name: NEXT_PUBLIC_FLAGS_AGENT
              value: c778cf4b-83f1-4c53-951e-604102c84898
            - name: NEXT_PUBLIC_FLAGS_PROJECT
              value: b0c5020e-760e-4156-a88b-344fb725a9b7
            - name: NEXT_PUBLIC_FLAGS_ENVIRONMENT
              value: 81aca98e-3b01-4c3c-a4cf-c7eee26185c5

---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: flags-gg
  labels:
    name: dashboard
    app: dashboard
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: dashboard

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard
  namespace: flags-gg
  annotations:
    cert-manager.io/cluster-issuer: live-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: dashboard
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dashboard.flags.gg
      secretName: dashboard-tls
  rules:
    - host: dashboard.flags.gg
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 3000
