export const DirectionMap = [
  {id: 'ArrowUp', icon: '🔼'},
  {id: 'ArrowDown', icon: '🔽'},
  {id: 'ArrowLeft', icon: '◀️'},
  {id: 'ArrowRight', icon: '▶️'},
]

export const LetterMap = [
  {id: 'a', icon: 'A'},
  {id: 'b', icon: 'B'},
  {id: 'c', icon: 'C'},
  {id: 'd', icon: 'D'},
  {id: 'e', icon: 'E'},
  {id: 'f', icon: 'F'},
  {id: 'g', icon: 'G'},
  {id: 'h', icon: 'H'},
  {id: 'i', icon: 'I'},
  {id: 'j', icon: 'J'},
  {id: 'k', icon: 'K'},
  {id: 'l', icon: 'L'},
  {id: 'm', icon: 'M'},
  {id: 'n', icon: 'N'},
  {id: 'o', icon: 'O'},
  {id: 'p', icon: 'P'},
  {id: 'q', icon: 'Q'},
  {id: 'r', icon: 'R'},
  {id: 's', icon: 'S'},
  {id: 't', icon: 'T'},
  {id: 'u', icon: 'U'},
  {id: 'v', icon: 'V'},
  {id: 'w', icon: 'W'},
  {id: 'x', icon: 'X'},
  {id: 'y', icon: 'Y'},
  {id: 'z', icon: 'Z'},
]

export const NumberMap = [
  {id: '0', icon: '0'},
  {id: '1', icon: '1'},
  {id: '2', icon: '2'},
  {id: '3', icon: '3'},
  {id: '4', icon: '4'},
  {id: '5', icon: '5'},
  {id: '6', icon: '6'},
  {id: '7', icon: '7'},
  {id: '8', icon: '8'},
  {id: '9', icon: '9'},
]
